name = "lovelace_workspace"
description = "Lovelace monorepo workspace aggregate"
version = "0.1.0-dev"

authors = ["Stefano Anelli"]
maintainers = ["Stefano Anelli <sanelli@users.noreply.github.com>"]
licenses = "MIT"

[[depends-on]]
lovelace = "*"
lovelace_common = "*"

[[pins]]
lovelace = { path = "lovelace" }
lovelace_common = { path = "common" }
