# Write Lovelace.Main.Git_Hash from the current git short hash (or "nogit").
# Invoked as an Alire pre-build action for the lovelace crate.

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
$Output = Join-Path $RepoRoot 'lovelace/src/lovelace-main-git_hash.ads'

$GitHash = 'nogit'
$PreviousPreference = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
$GitOutput = & git -C $RepoRoot rev-parse --short HEAD 2>$null
$GitExitCode = $LASTEXITCODE
$ErrorActionPreference = $PreviousPreference

if ($GitExitCode -eq 0 -and -not [string]::IsNullOrWhiteSpace($GitOutput)) {
    $GitHash = ([string]$GitOutput).Trim()
}

$Contents = @"
--  Generated by scripts/embed-git-hash.ps1 at build time; do not edit or commit.

package Lovelace.Main.Git_Hash is

   --  Short git object name, or nogit when unavailable at build time.
   Git_Hash : constant String := "$GitHash";

end Lovelace.Main.Git_Hash;
"@

[System.IO.File]::WriteAllText($Output, $Contents)
